spring.application.name=TurboTikects-server
# Server Configuration
server.port=3000

# Database Configuration (MySQL Example)
spring.datasource.url=jdbc:mysql://localhost:3306/cmdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings (Optional but helpful)
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.jpa.hibernate.ddl-auto=none
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.ignore-migration-patterns=*:*
spring.flyway.out-of-order=true
spring.flyway.validate-on-migrate=false

infinispan.embedded.config-xml=infinispan.xml


app.cors.origins=http://localhost:5173/

app.ldap.encryption-key=change-me-to-a-secret-32-char-key
