CREATE TABLE ssl_settings (
    id                 INT          NOT NULL DEFAULT 1,
    enabled            TINYINT(1)   NOT NULL DEFAULT 0,
    cert_type          VARCHAR(20)  NULL,
    domain             VARCHAR(500) NULL,
    keystore_path      VARCHAR(500) NULL,
    keystore_password  VARCHAR(200) NULL,
    https_port         INT          NOT NULL DEFAULT 3443,
    cert_subject       VARCHAR(500) NULL,
    cert_issuer        VARCHAR(500) NULL,
    cert_expiry        DATETIME     NULL,
    created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

INSERT INTO ssl_settings (id, enabled) VALUES (1, 0);

INSERT INTO dynamic_translations (lang_code, translation_key, translated_text, type) VALUES
('en', 'ssl_title',               'SSL / TLS Certificate',                                                                              'system'),
('en', 'ssl_desc',                'Secure your system with HTTPS by installing an SSL/TLS certificate.',                                 'system'),
('en', 'ssl_status_label',        'Status',                                                                                              'system'),
('en', 'ssl_status_enabled',      'Active',                                                                                              'system'),
('en', 'ssl_status_disabled',     'Not configured',                                                                                      'system'),
('en', 'ssl_cert_type_label',     'Certificate type',                                                                                    'system'),
('en', 'ssl_cert_type_self',      'Self-signed',                                                                                         'system'),
('en', 'ssl_cert_type_public',    'Publicly trusted',                                                                                    'system'),
('en', 'ssl_domain_label',        'Domain / Hostname',                                                                                   'system'),
('en', 'ssl_https_port_label',    'HTTPS port (inside container)',                                                                       'system'),
('en', 'ssl_format_label',        'Upload format',                                                                                       'system'),
('en', 'ssl_format_pem',          'PEM files (cert + key)',                                                                              'system'),
('en', 'ssl_format_pkcs12',       'PKCS12 bundle (.p12 / .pfx)',                                                                        'system'),
('en', 'ssl_cert_file_label',     'Certificate file (.pem / .crt)',                                                                      'system'),
('en', 'ssl_key_file_label',      'Private key file (.pem / .key)',                                                                      'system'),
('en', 'ssl_p12_file_label',      'PKCS12 bundle (.p12 / .pfx)',                                                                        'system'),
('en', 'ssl_p12_password_label',  'PKCS12 password',                                                                                    'system'),
('en', 'ssl_install_btn',         'Install certificate',                                                                                 'system'),
('en', 'ssl_remove_btn',          'Remove certificate',                                                                                  'system'),
('en', 'ssl_remove_confirm',      'Remove the SSL certificate and restart the server on HTTP only?',                                     'system'),
('en', 'ssl_cert_info_title',     'Current certificate',                                                                                 'system'),
('en', 'ssl_cert_subject',        'Subject',                                                                                             'system'),
('en', 'ssl_cert_issuer',         'Issuer',                                                                                              'system'),
('en', 'ssl_cert_expiry',         'Expires',                                                                                             'system'),
('en', 'ssl_cert_domain',         'Domain',                                                                                              'system'),
('en', 'ssl_restarting_title',    'Server is restarting',                                                                                'system'),
('en', 'ssl_restarting_msg',      'SSL has been configured. The server will restart in a few seconds and you will be redirected to HTTPS.', 'system'),
('en', 'ssl_removing_msg',        'SSL certificate removed. The server will restart and you will be redirected to HTTP.',                 'system'),
('en', 'ssl_docker_note',         'Make sure your docker-compose maps the HTTPS port to the host (e.g. "443:3443") before restarting.',  'system'),
('en', 'ssl_redirect_seconds',    'Redirecting in',                                                                                      'system'),
('en', 'ssl_redirect_seconds_unit', 'seconds',                                                                                           'system'),
('en', 'ssl_error_invalid_cert',  'Invalid or unreadable certificate file.',                                                             'system'),
('en', 'ssl_error_key_mismatch',  'The private key does not match the certificate.',                                                     'system'),
('en', 'ssl_error_cert_expired',  'The certificate has already expired.',                                                                'system'),
('en', 'ssl_error_bad_pkcs12',    'Invalid PKCS12 file or wrong password.',                                                              'system'),
('en', 'ssl_installed_label',     'Installed',                                                                                           'system'),
('en', 'ssl_port_label',          'HTTPS port',                                                                                          'system'),
('en', 'ssl_install_replace_note','Installing a new certificate will replace the current one and restart the server.',                   'system');

INSERT INTO dynamic_translations (lang_code, translation_key, translated_text, type) VALUES
('en', 'setup_ssl_title',         'SSL / TLS Certificate',                                                                              'system'),
('en', 'setup_ssl_desc',          'Install an SSL certificate to serve your ticketing system over HTTPS.',                               'system'),
('en', 'setup_ssl_s1',            'Go to System Security → SSL / TLS Certificate',                                                      'system'),
('en', 'setup_ssl_s2',            'Upload a PEM certificate + private key pair, or a PKCS12 bundle',                                    'system'),
('en', 'setup_ssl_s3',            'Set the HTTPS port and click Install',                                                               'system'),
('en', 'setup_ssl_s4',            'Update your docker-compose to map the HTTPS port (e.g. 443:3443) and restart',                       'system'),
('en', 'setup_ssl_btn',           'Go to SSL Settings',                                                                                  'system');
