INSERT IGNORE INTO dynamic_translations (lang_code, translation_key, translated_text, type) VALUES
('en', 'acceleration_combinator_label',     'Match',                                              'system'),
('en', 'acceleration_combinator_and',       'ALL conditions (AND)',                                'system'),
('en', 'acceleration_combinator_or',        'ANY condition (OR)',                                  'system'),
('en', 'acceleration_conditions_hint_and',  'ALL conditions must be true for the rule to apply.', 'system'),
('en', 'acceleration_conditions_hint_or',   'At least ONE condition must be true.',               'system'),
('en', 'acceleration_op_contains',          'Contains',                                           'system'),
('en', 'acceleration_op_not_contains',      'Does Not Contain',                                   'system'),
('en', 'acceleration_op_lt',                'Less Than',                                          'system'),
('en', 'acceleration_op_gt',                'Greater Than',                                       'system'),
('en', 'acceleration_op_is_true',           'Is Checked',                                         'system'),
('en', 'acceleration_op_is_false',          'Is Unchecked',                                       'system'),
('en', 'acceleration_op_older_than',        'Older Than',                                         'system'),
('en', 'acceleration_op_newer_than',        'Newer Than',                                         'system'),
('en', 'acceleration_unit_minutes',         'Minutes',                                            'system'),
('en', 'acceleration_unit_hours',           'Hours',                                              'system'),
('en', 'acceleration_unit_days',            'Days',                                               'system'),
('en', 'acceleration_system_fields_group',  'System Fields',                                      'system'),
('en', 'acceleration_custom_fields_group',  'Custom Fields',                                      'system'),
('en', 'acceleration_add_group_btn',        'Add Group',                                          'system'),
('en', 'acceleration_group_label',          'Condition Group',                                    'system');
