package com.turbotikects.turbotikectsserver.dto;

import lombok.Data;

import java.util.List;
import java.util.Map;

/**
 * "Fix/adjust with AI" — external_api Field Mapping and Test steps of the guided wizard flow. The
 * admin asks the AI to adjust the one call's mapping/URL — either because a real test just failed
 * (an error is given) or just because they want to change something (no error given) — continuing
 * the SAME AiChatSession the wizard's earlier steps (aiDiscoverEndpoints/aiDraftCallSkeleton/
 * aiMapCallFields) already used, so the AI still has the original documentation/intent/field-
 * mapping context, not just this one call in isolation. See TemplateService.aiFixCall's javadoc.
 */
@Data
public class AiFixCallRequestDto {
    private Long sessionId;
    private String documentation;
    private String intent;
    /** Free-text admin instruction, e.g. "use the real SerpAPI Google Flights endpoint". */
    private String instructions;
    /** The test failure message shown to the admin, if this follows a failed test — grounds the fix in what actually went wrong; omitted when the admin is just asking for a change. */
    private String error;
    /** The one call being adjusted, same shape aiDraftCallSkeleton produces (id/order/responseCaptures are preserved verbatim, never regenerated by the AI). */
    private Map<String, Object> call;
    /** The entry's current fieldMappings.request, so the AI knows what's already mapped and doesn't duplicate/orphan placeholders. */
    private List<Map<String, Object>> requestMappings;
    private List<WorkflowFieldRefDto> ticketFields;
    private List<WorkflowFieldRefDto> workflowFields;
}
